// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgmYim3IN5UmNUo3LPlDHdLEkt_WEXys',
    appId: '1:772886464594:web:4348ea3497c5b4625c378b',
    messagingSenderId: '772886464594',
    projectId: 'my-project-859f5',
    authDomain: 'my-project-859f5.firebaseapp.com',
    storageBucket: 'my-project-859f5.appspot.com',
    measurementId: 'G-FQQH5HNB61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgIf8BIz9l1HpjTqvtIAWN3xYudk0XSg',
    appId: '1:772886464594:android:70d3f87bf253f08f5c378b',
    messagingSenderId: '772886464594',
    projectId: 'my-project-859f5',
    storageBucket: 'my-project-859f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9P2fjXIwkF20mG1-GWodwHabrNj8zQaE',
    appId: '1:772886464594:ios:6eb0e29af01879245c378b',
    messagingSenderId: '772886464594',
    projectId: 'my-project-859f5',
    storageBucket: 'my-project-859f5.appspot.com',
    iosClientId: '772886464594-ecn8a15uiuiip7qhq98oq0aasujf5gjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9P2fjXIwkF20mG1-GWodwHabrNj8zQaE',
    appId: '1:772886464594:ios:6eb0e29af01879245c378b',
    messagingSenderId: '772886464594',
    projectId: 'my-project-859f5',
    storageBucket: 'my-project-859f5.appspot.com',
    iosClientId: '772886464594-ecn8a15uiuiip7qhq98oq0aasujf5gjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdgmYim3IN5UmNUo3LPlDHdLEkt_WEXys',
    appId: '1:772886464594:web:45cb597a29af6e745c378b',
    messagingSenderId: '772886464594',
    projectId: 'my-project-859f5',
    authDomain: 'my-project-859f5.firebaseapp.com',
    storageBucket: 'my-project-859f5.appspot.com',
    measurementId: 'G-0YWCWRKVHW',
  );
}
